### ISSUE TITLE
WSOD with hudge headers

### ISSUE THREAD

**Issue by lbodiguel** [wodby/varnish#1]
Hi,

On our dev environments, we've got the following drupal setting set to true on our development.services.yml :
`http.response.debug_cacheability_headers: true`

With some huge content types, create/edit forms reponses sends an extremly large `X-Drupal-Cache-Tags` header, which breaks varnish with the following error : 

`BogoHeader     Header too long: X-Drupal-Cache-Tags`

We've found a dirty workaround by setting `VARNISHD_THREAD_POOL_MAX` to `1000 -p http_resp_hdr_len=65536 -p http_resp_size=98304` since `VARNISHD_THREAD_POOL_MAX` is the last used variable.

Would it be possible to add `VARNISHD_RESP_HDR_LEN` and `VARNISHD_HTTP_RESP_SIZE` to the available variables please ?

Thank you !

**Comment by csandanov** [comment]
Additional env vars to control varnishd params have been added and available in tags `latest` and stability tag [`2.3.0`](https://github.com/wodby/varnish/releases), i.e. `wodby/varnish:4-2.3.0`
