### ISSUE TITLE
Support of WooCommerce cart cookies

### ISSUE THREAD

**Issue by PavelPrischepa** [wodby/varnish#11]
WooCommerce may use [3 cookies](https://docs.woocommerce.com/document/woocommerce-cookies/) for anonymous users:
- woocommerce_cart_hash
- woocommerce_items_in_cart
- wp_woocommerce_session_

We need a way to avoid caching for such cookies and probably for some paths:
- /cart
- /my-account
- /checkout
- /addons
- ?add-to-cart=
- /add-to-cart

Actually, I'm not sure about paths because cookies exclusion should be enough but I see a few examples of WooCommerce integration with both cookies and paths exclusion. It seems it should be tested additionally.

I suggest to implement a generic way to exclude caching for cookies and paths.

**Comment by maxrev17** [comment]
Is there an estimate on when this may be completed/released?

**Comment by csandanov** [comment]
Added support for woocommerce cookies, exclude for specific URLs makes sense because they should normally set `Cache-control: no-cache` header that respected by Varnish.
