### ISSUE TITLE
Possible config issues

### ISSUE THREAD

**Issue by PavelPrischepa** [wodby/varnish#12]
I noticed possible issue in varnish config:

1. https://github.com/wodby/varnish/blob/master/templates/defaults/vcl_recv.vcl.tmpl#L34 
```
"^[; ]+|[; ]+$"
```
a regexp consists of 2 identical parts `[; ]`

2. It seems cookies does not affect hash [here](https://github.com/wodby/varnish/blob/master/templates/defaults/vcl_hash.vcl.tmpl), so [this block](https://github.com/wodby/varnish/blob/master/templates/defaults/vcl_recv.vcl.tmpl#L36) looks useless. I tested with `FooCookieName=BarValue` cookie and it does not affect on cache hash (`VARNISH_KEEP_ALL_COOKIES` was not enabled).

**Comment by csandanov** [comment]
This means delete `;` at the start and the end.

**Comment by csandanov** [comment]
We also use in Drupal preset and it's commented as:

>        # 5. Remove all spaces and semi-colons from the beginning and end of the
>        #    cookie string.
