### ISSUE TITLE
Arm images missing

### ISSUE THREAD

**Issue by back-2-95** [wodby/varnish#31]
We're getting 1st Apple M1 devices and we saw that Varnish image has no arm build.

**Comment by back-2-95** [comment]
@csandanov ?

**Comment by csandanov** [comment]
we have issues while testing libvmod geoip module on arm64 https://github.com/varnish/libvmod-geoip/issues/19

https://github.com/wodby/varnish/runs/2858874440?check_suite_focus=true

**Comment by back-2-95** [comment]
Is it a dead end?

**Comment by csandanov** [comment]
@back-2-95 could you please test the latest version of the image, tests pass on graviton but I'm not sure about M1

**Comment by back-2-95** [comment]
@csandanov I did test on one project and it seems to work. Container stays up & I can browse the Drupal site through Varnish.
Big Sur 11.5 on M1.
