### ISSUE TITLE
Varnish is not compiling - container exit code 2

### ISSUE THREAD

**Issue by pasim** [wodby/varnish#32]
I am facing some real issues while ruining wodby/varnish:4-4.6.4 container - Varnish does not compile.
Here is the error from logs:
wodby/varnish:4-4.6.4
`Error:
 Running VCC-compiler failed, signal 5
VCL compilation failed
`
The environment for me:
`docker run -it --rm -e VARNISH_BACKEND_HOST=localhost -e VARNISH_BACKEND_PORT=8080 -e VARNISH_CONFIG_PRESET=drupal wodby/varnish:4-4.6.4`

**Comment by csandanov** [comment]
Our current [tests](https://github.com/wodby/varnish/tree/master/tests) pass without any issues on arm64 (run `make test`). How can I reproduce it?

**Comment by pasim** [comment]
@csandanov see my command from above:
`docker run -it --rm -e VARNISH_BACKEND_HOST=localhost -e VARNISH_BACKEND_PORT=8080 -e VARNISH_CONFIG_PRESET=drupal wodby/varnish:4-4.6.4`

**Comment by csandanov** [comment]
You are connecting varnish to a `localhost:8080` inside varnish container and there's nothing else except varnish running in its container. Please see how we run our tests. 

Also, see #31, there's no arm64 support yet
