### ISSUE TITLE
varnish cache tag invalidation not working with drupal 8.

### ISSUE THREAD

**Issue by genebobmiller** [wodby/varnish#33]
Using the Varnish Purge module with the following headers set:

Cache-Tags: [invalidation:expression]
X-VC-Purge-Key: <the key>

never seems to invalidate.

I believe this is due to the wodby image vcl looking for the `Cache-Tags` header when drupal is returning `X-Drupal-Cache-Tags`.
The attached patch seems to fix the issue.

```
diff --git a/templates/includes/purge.vcl.tmpl b/templates/includes/purge.vcl.tmpl
index e30e2b1..aef0de8 100755
--- a/templates/includes/purge.vcl.tmpl
+++ b/templates/includes/purge.vcl.tmpl
@@ -48,8 +48,8 @@ sub vcl_recv {
         {{ end }}
         {{ end }}
 
-        if (req.method == "BAN" && req.http.Cache-Tags) {
-            ban("obj.http.Cache-Tags ~ " + req.http.Cache-Tags);
+        if (req.method == "BAN" && req.http.X-Drupal-Cache-Tags) {
+            ban("obj.http.X-Drupal-Cache-Tags ~ " + req.http.X-Drupal-Cache-Tags);
         }
 
         if (req.http.X-VC-Purge-Method) {
 ```

**Comment by csandanov** [comment]
Module https://www.drupal.org/project/varnish_purge still uses `Cache-Tags` header. I believe `X-Drupal-Cache-Tags` used for debugging. Also see https://www.drupal.org/docs/drupal-apis/cache-api/cache-tags-varnish

**Comment by genebobmiller** [comment]
Thanks Chingis! 

Enabling the Purge Tokens module added the necessary Cache-Tags header.
