### ISSUE TITLE
Add mod digest

### ISSUE THREAD

**Issue by sirdiego** [wodby/varnish#37]
Hi, can you add [vmod_digest](https://github.com/varnish/libvmod-digest) to this image?

I tried compiling it after but from my understanding that is not possible, because you delete all the relevant header files. See the [README](https://github.com/varnish/libvmod-digest#installation).

Otherwise the installation seems to be very similar to vmod_geoip.

**Comment by csandanov** [comment]
Sure, you can submit a PR
