### ISSUE TITLE
Connection="Close" is commented, maybe it should not.

### ISSUE THREAD

**Issue by killfill** [wodby/varnish#6]
Hi @csandanov 

Was just reading up some modifications. Haven't really use them (shame on me!), but before i forget: about this line:

https://github.com/wodby/varnish/blob/master/4/templates/defaults/vcl_pipe.vcl.tmpl#L22

That Connection="Close" should not be commented out, should it?

Thanks!!

**Comment by csandanov** [comment]
You're right, thanks!
