### ISSUE TITLE
Add support of GeoIP switching in a generic fashion

### ISSUE THREAD

**Issue by PavelPrischepa** [wodby/varnish#8]
It seems we should add support of GeoIP switching in a generic fashion. Here is an example of [WooCommerce currency switching](https://guides.wp-bullet.com/cache-woocommerce-currency-from-cloudflare-geoip-with-varnish-4/) for WordPress.

UPD1: It could be implemented in a generic way as described in #9, so we do not need to hardcode any special.

**Comment by csandanov** [comment]
Since [4.0.0](https://github.com/wodby/varnish/releases/tag/4.0.0) we now have geoip module and detect country code / currency. Also support CF header.
