### ISSUE TITLE
Customize cache hash key via cookies

### ISSUE THREAD

**Issue by PavelPrischepa** [wodby/varnish#9]
We should consider adding [such functionality](https://pantheon.io/docs/caching-advanced-topics/#using-styxkey) to varnish image. It will allow us to have different versions of content for the same URL. Different versions for a country, for a currency, for a device and whatever a user wants. It's generic, flexible and easy to use.

Also we may ditch such hardcode https://github.com/wodby/varnish/blob/master/4/templates/includes/mobile.vcl.tmpl.

**Comment by csandanov** [comment]
Since [4.0.0](https://github.com/wodby/varnish/releases/tag/4.0.0) we now have `VCKEY-`
